### PR TITLE
Upgrade to Orchard Core RC1

### PR DESCRIPTION
**Pull request by mobinzk**
- Update readme
- Update recipe
- Update to .netcore3.0
- Bump version number

### CODE REVIEW

**Comment by peterkeating** [comment]
@mobinzk To make the dev ops builds pass you need to update the build files to use a different vm. See https://github.com/EtchUK/Etch.OrchardCore.Fields/blob/upgrade/rc1/azure-pipeline-preview.yml#L2 for an example of what needs to be changed.

**Comment by peterkeating** [comment]
@mobinzk Can you change the version suffix from "beta" to "rc1".

**Review by peterkeating — CHANGES_REQUESTED** [review]
@mobinzk Can you change the version suffix from "beta" to "rc1".

**Comment by mobinzk** [comment]
@peterkeating Done this, Also squashed all 3 commits to one.

**Review by peterkeating — APPROVED** [review]

**Pull request merged**
